version: '3.3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrtpwd
      MYSQL_DATABASE: joomladb
      MYSQL_USER: joomlauser
      MYSQL_PASSWORD: joomlapassword
    networks:
      - private

  joomla:
    image: apache:2.0
    ports:
      - 80
    restart: always
    networks:
      - public
      - private
    depends_on:
      - mysql

networks:
  public:
    driver: bridge
  private:
    driver: bridge
